/**
 * AIGC Forensics — Image Authenticity Lab & Physical Evidence Station
 * Three.js Real-time 3D PBR Workstation & GSAP Flip Card Physics Engine
 */

function resolveApiBaseUrl() {
  if (typeof window !== "undefined" && window.__AIGC_API_BASE_URL__) {
    return window.__AIGC_API_BASE_URL__;
  }
  if (typeof window !== "undefined") {
    const host = window.location.hostname;
    if (
      host === "manansethia.com" ||
      host === "www.manansethia.com" ||
      host === "techjam.manansethia.com" ||
      host === "tiktoktechjam2026.manansethia.com"
    ) {
      return "https://api.manansethia.com";
    }
    if (window.location.port === "3000") {
      return `${window.location.protocol}//${window.location.hostname}:8000`;
    }
    return window.location.origin;
  }
  return "";
}

// Application State
const STATE = {
  apiBaseUrl: resolveApiBaseUrl(),
  items: [],
  results: [],
  selectedCard: null,
  activeMode: "HEAT",
  activeReplayStage: "ingest",
  isAnalyzing: false,
  deckOffset: 0,
  stagedCardId: null,
  piles: {
    REAL: [],
    PARTIAL_AI: [],
    FULL_AIGC: []
  }
};

function getAnalysisSessionId() {
  const key = "aigc-forensics-session-id";
  let sessionId = sessionStorage.getItem(key);
  if (!sessionId) {
    sessionId = `sess_${Date.now().toString(36)}_${crypto.getRandomValues(new Uint32Array(3)).join("_")}`;
    sessionStorage.setItem(key, sessionId);
  }
  return sessionId;
}

// 10 Comprehensive High-Fidelity Pre-Configured Benchmark Cases
const DEMO_CASES = [
  {
    id: "AF-7C21",
    filename: "canon_eos_r5_portrait.jpg",
    title: "Canon EOS R5 Portrait (Authentic)",
    url: "/assets/evidence-lake.jpg",
    dimensions: "6016 × 4016",
    verdict: "REAL",
    verdict_badge: "AUTHENTIC PHOTOGRAPH",
    verdict_desc: "Authentic camera capture. Natural PRNU sensor noise and optical chromatic dispersion verified across red/green channels.",
    probability_aigc: 0.015,
    affected_area: 0.0,
    confidence_tier: "HIGH CONFIDENCE",
    inconsistency_status: "CLEAN PASS",
    inconsistency_color: "var(--emerald)",
    fft_high_freq: "0.0412",
    fft_bar: 12,
    srm_energy: "1.8420",
    srm_bar: 24,
    lap_var: "142.5",
    lap_bar: 38,
    gate_clip: 0.38,
    gate_siglip: 0.42,
    gate_srm: 0.20,
    camera: "Canon EOS R5",
    lens: "RF 85mm f/1.2L USM",
    exposure: "1/500s · f/1.4 · ISO 100",
    c2pa: "NOT DETECTED",
    sha256: "7c21a4f89d3e0b2a65d14e9f7832bc90fa12e65d83c276104e19572ba89c3140",
    provenance_headline: "STANDARD RAW / JFIF CONTAINER",
    provenance_body: "Canon CR3 pipeline; authentic Bayer color filter array pattern intact."
  },
  {
    id: "AF-3B94",
    filename: "magic_editor_infill.jpg",
    title: "Google Magic Editor Infill (4.2% Area)",
    url: "/assets/evidence-city.jpg",
    dimensions: "4032 × 3024",
    verdict: "PARTIAL_AI",
    verdict_badge: "LOCALIZED AI MANIPULATION",
    verdict_desc: "Authentic photograph with localized generative inpainting (~4.2% affected area). SRM residual filter isolates clear boundary blend seam.",
    probability_aigc: 0.642,
    affected_area: 4.2,
    confidence_tier: "HIGH CONFIDENCE",
    inconsistency_status: "ANOMALY DETECTED",
    inconsistency_color: "var(--amber)",
    fft_high_freq: "0.1420",
    fft_bar: 52,
    srm_energy: "4.9520",
    srm_bar: 68,
    lap_var: "385.2",
    lap_bar: 72,
    gate_clip: 0.25,
    gate_siglip: 0.35,
    gate_srm: 0.40,
    camera: "Google Pixel 8 Pro",
    lens: "6.9mm f/1.68",
    exposure: "1/120s · f/1.68 · ISO 52",
    c2pa: "PRESENT (MODIFIED)",
    sha256: "3b94e82c10a47f5d91823bc047ea6102f9284da721bc695e148203f7194685ab",
    provenance_headline: "GOOGLE PHOTOS MAGIC EDITOR",
    provenance_body: "C2PA manifest confirms selective object removal and generative inpainting."
  },
  {
    id: "AF-9F40",
    filename: "flux1_studio_portrait.png",
    title: "FLUX.1 Photoreal Studio Portrait",
    url: "/assets/evidence-coast.jpg",
    dimensions: "2048 × 2048",
    verdict: "FULL_AIGC",
    verdict_badge: "SYNTHETIC IMAGE",
    verdict_desc: "Synthetic image generated by generative diffusion model. 2D FFT exhibits characteristic 45-degree lattice harmonics.",
    probability_aigc: 0.988,
    affected_area: 96.4,
    confidence_tier: "HIGH CONFIDENCE",
    inconsistency_status: "ANOMALY DETECTED",
    inconsistency_color: "var(--crimson)",
    fft_high_freq: "0.2840",
    fft_bar: 88,
    srm_energy: "6.4210",
    srm_bar: 92,
    lap_var: "684.0",
    lap_bar: 95,
    gate_clip: 0.45,
    gate_siglip: 0.45,
    gate_srm: 0.10,
    camera: "NOT PRESENT (STRIPPED)",
    lens: "N/A",
    exposure: "N/A",
    c2pa: "NOT DETECTED",
    sha256: "9f4081c73a2e5d910b84c317f2905e46da8129e01f5c76384219ef84a10738bc",
    provenance_headline: "COMFYUI / FLUX.1 LATENT SYNTHESIS",
    provenance_body: "No physical sensor PRNU pattern; high-order wavelet details lack optical grain."
  },
  {
    id: "AF-4E10",
    filename: "sdxl_object_insertion.jpg",
    title: "SDXL Object Insertion (8.4% Area)",
    url: "/assets/evidence-city.jpg",
    dimensions: "5472 × 3648",
    verdict: "PARTIAL_AI",
    verdict_badge: "LOCALIZED AI MANIPULATION",
    verdict_desc: "Synthetic object insertion detected (~8.4% area). Multi-scale patch encoder isolates token divergence on wrist element.",
    probability_aigc: 0.710,
    affected_area: 8.4,
    confidence_tier: "HIGH CONFIDENCE",
    inconsistency_status: "ANOMALY DETECTED",
    inconsistency_color: "var(--amber)",
    fft_high_freq: "0.1650",
    fft_bar: 58,
    srm_energy: "5.1200",
    srm_bar: 70,
    lap_var: "412.0",
    lap_bar: 76,
    gate_clip: 0.30,
    gate_siglip: 0.30,
    gate_srm: 0.40,
    camera: "Fujifilm X-T4",
    lens: "XF56mmF1.2 R",
    exposure: "1/320s · f/2.0 · ISO 160",
    c2pa: "NOT DETECTED",
    sha256: "4e1078a9c2b104f65d3810294e7b8c91a0521e43896541f7203b519a4e82910c",
    provenance_headline: "SDXL INPAINT COMPOSITE",
    provenance_body: "Localized inpainting layer identified with seam boundary spectral shift."
  },
  {
    id: "AF-1A88",
    filename: "sony_a7iv_urban.jpg",
    title: "Sony A7 IV Urban Scene (Authentic)",
    url: "/assets/evidence-lake.jpg",
    dimensions: "7008 × 4672",
    verdict: "REAL",
    verdict_badge: "AUTHENTIC PHOTOGRAPH",
    verdict_desc: "Authentic photograph redistributed with JPEG compression. High-level semantic geometry and natural optical perspective verified.",
    probability_aigc: 0.075,
    affected_area: 0.0,
    confidence_tier: "HIGH CONFIDENCE",
    inconsistency_status: "COMPRESSION DEGRADED",
    inconsistency_color: "#a39e91",
    fft_high_freq: "0.0380",
    fft_bar: 15,
    srm_energy: "2.1500",
    srm_bar: 28,
    lap_var: "82.4",
    lap_bar: 22,
    gate_clip: 0.50,
    gate_siglip: 0.40,
    gate_srm: 0.10,
    camera: "Sony ILCE-7M4",
    lens: "FE 35mm F1.4 GM",
    exposure: "1/250s · f/2.8 · ISO 400",
    c2pa: "NOT DETECTED",
    sha256: "1a884f901c238b75e1940285a417e290f6b38421e059174823a04f7182934105",
    provenance_headline: "STANDARD JFIF CONTAINER",
    provenance_body: "Sony ARW processed container, natural glass micro-contrast intact."
  },
  {
    id: "AF-8D20",
    filename: "midjourney_v6_concept.png",
    title: "Midjourney v6 Cinematic Concept",
    url: "/assets/evidence-coast.jpg",
    dimensions: "2912 × 1632",
    verdict: "FULL_AIGC",
    verdict_badge: "SYNTHETIC IMAGE",
    verdict_desc: "Synthetic image. Characteristic texture oversmoothing in wavelet high-frequency sub-bands with zero camera sensor noise.",
    probability_aigc: 0.974,
    affected_area: 98.1,
    confidence_tier: "HIGH CONFIDENCE",
    inconsistency_status: "ANOMALY DETECTED",
    inconsistency_color: "var(--crimson)",
    fft_high_freq: "0.2650",
    fft_bar: 84,
    srm_energy: "6.1800",
    srm_bar: 89,
    lap_var: "630.0",
    lap_bar: 91,
    gate_clip: 0.48,
    gate_siglip: 0.44,
    gate_srm: 0.08,
    camera: "NOT PRESENT (STRIPPED)",
    lens: "N/A",
    exposure: "N/A",
    c2pa: "NOT DETECTED",
    sha256: "8d20b4197e3a1f0c294851e73a019485f8120394851e739281a049581729384a",
    provenance_headline: "MIDJOURNEY V6 PROFILE",
    provenance_body: "Generative latent diffusion synthesis; zero physical sensor PRNU profile."
  }
];

// Documentation Modal Contents
const DOC_CONTENTS = {
  about: `
    <div style="font-family: var(--system); color: var(--ivory); line-height: 1.75;">
      <h1 style="font-family: var(--condensed); font-size: 36px; color: var(--ivory); margin: 0 0 16px; letter-spacing: 1px;">WHY AIGC FORENSICS MATTERS</h1>
      <p style="font-size: 15px; color: #c5beaf; margin-bottom: 16px;">As modern generative models (FLUX.1, SDXL, Midjourney v6, Google Imagen 3, and DALL-E 3) achieve unprecedented photorealism, human visual inspection is no longer a viable defense. Authentic photojournalism, judicial evidence, insurance claims, and digital archives face critical threats from undetectable synthetic manipulations.</p>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px; letter-spacing: 0.5px;">THE CRITICAL PROBLEM: LOCALIZED EDITING &amp; INPAINTING</h2>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 12px;">Most commercial and academic AI detectors frame the problem as binary: 100% Real vs. 100% Synthetic. However, real-world digital creators rarely replace entire photographs. Instead, they apply localized generative inpainting (such as Google Magic Editor, Adobe Generative Fill, or face-swapping) to modify only 1% to 10% of an otherwise authentic photograph.</p>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 16px;">Standard global vision classifiers mean-pool whole-image tokens across the entire canvas, diluting localized 3% inpainting traces into the 97% authentic background and generating dangerous false negatives.</p>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px; letter-spacing: 0.5px;">REDISTRIBUTION &amp; SOCIAL MEDIA ROBUSTNESS</h2>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 12px;">When images are shared on social platforms (TikTok, Instagram, WhatsApp, X), they are subjected to aggressive lossy JPEG compression (Q &isin; [30, 70]), bicubic downscaling, Gaussian blur, and color adjustments. Detectors that rely solely on pristine high-frequency Fourier grid artifacts collapse under redistribution.</p>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 24px;">Our project, built by <strong>Manan Sethia</strong>, addresses this challenge by decoupling semantic coherence from high-frequency noise residuals, enabling robust detection across raw DSLR captures and compressed social media files alike.</p>

      <div style="background: rgba(212, 175, 55, 0.08); border-left: 3px solid #ffaa44; padding: 18px 22px; margin: 28px 0; border-radius: 4px;">
        <h3 style="font-family: var(--condensed); font-size: 20px; color: #ffaa44; margin: 0 0 12px; letter-spacing: 0.5px;">KNOWN FORENSIC BLINDSPOTS &amp; CURRENT LIMITATIONS (HONEST SCIENCE)</h3>
        <p style="font-size: 13px; color: #c5beaf; margin-bottom: 12px;">In the spirit of rigorous, transparent forensic science, we document the specific edge-case domains where single-image forensic models encounter physical and statistical ambiguity:</p>
        <ul style="font-size: 13px; color: #b0aa9c; padding-left: 18px; line-height: 1.85;">
          <li><strong>Ultra-High-Resolution Scenic &amp; Landscape Captures (&gt;2048px / 60MP)</strong>: Extreme optical micro-contrast from dense foliage, grass blades, and distant architecture produces high-frequency directional energy that can mimic synthetic upsampling grids unless multi-scale patch voting is applied.</li>
          <li><strong>Astrophotography &amp; Deep Sky Imagery</strong>: Long-exposure captures, high-ISO sensor shot noise (ISO 6400+), star-stacking algorithms, and cosmic ray removal introduce non-standard spatial noise profiles that differ significantly from natural daylight scene distributions.</li>
          <li><strong>Screenshots, UI Renders &amp; Rasterized Graphic Design</strong>: Vector text overlays, crisp pixel-aligned interface buttons, and digital line art lack physical optical lens characteristics and Bayer filter color filter arrays (CFA), producing edge gradients that can trigger localized anomaly alerts.</li>
          <li><strong>Subtle Non-Generative Photoshop / Lightroom Adjustments</strong>: Classical digital darkroom operations (Clarity sliders, Unsharp Mask, selective dodging/burning, contrast curves, and chromatic aberration removal) modify local gradient distributions without being AI-generated, creating boundary ambiguity between synthetic generation and post-processing.</li>
        </ul>
      </div>
    </div>
  `,

  technology: `
    <div style="font-family: var(--system); color: var(--ivory); line-height: 1.75;">
      <h1 style="font-family: var(--condensed); font-size: 36px; color: var(--ivory); margin: 0 0 16px; letter-spacing: 1px;">FORENSIC NEURAL ARCHITECTURE</h1>
      
      <div style="background: rgba(212, 175, 55, 0.08); border-left: 3px solid var(--brass-hi); padding: 14px 18px; margin-bottom: 24px; border-radius: 4px;">
        <strong style="color: var(--brass-hi); font-size: 15px;">ACTIVE PRODUCTION ENGINE: Model C0 (Triple-Hybrid Champion ~735M Params)</strong>
        <p style="font-size: 13px; color: #c5beaf; margin: 6px 0 0;">This live analysis station is powered by the <strong>Triple-Hybrid Champion Anchor (Model C0)</strong>, combining multi-modal semantic transformer representations with high-pass spatial wavelet residual analysis.</p>
      </div>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 24px 0 10px;">PRIMARY LIVE SERVER MODEL: TRIPLE-HYBRID (C0, 735M)</h2>
      <ul style="font-size: 14px; color: #b0aa9c; padding-left: 20px; line-height: 1.8;">
        <li><strong>Stream A: OpenAI CLIP ViT-L/14</strong> (Frozen, 304M params) &mdash; Encodes macro-semantic consistency, anatomical geometry, perspective vanishing points, and scene lighting realism.</li>
        <li><strong>Stream B: Google SigLIP SO400M</strong> (Frozen, 400M params) &mdash; Captures fine-grained multi-modal semantic alignments, texture realism, and subtle photorealism discrepancies.</li>
        <li><strong>Stream C: Spatial Rich Model (SRM) + Haar Wavelet + ConvNeXt Trunk</strong> (31M params) &mdash; Extracts high-pass frequency residuals, upsampling lattice artifacts, and localized gradient discontinuities.</li>
        <li><strong>Bottleneck Cross-Fusion Head</strong> &mdash; Dynamically weights evidence streams via softmax reliability routing before generating calibrated posterior class probabilities.</li>
        <li><strong>Temperature Scaling Calibration</strong> &mdash; Calibrated via temperature parameter ($T = 1.5230$) to enforce strict false-positive bounds (FPR &le; 0.10%).</li>
      </ul>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">THE NEW STANDALONE DISTILLED MODELS (96.59M &amp; 4.67M)</h2>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 12px;">In addition to the C0 server anchor, we have trained standalone distilled models that operate with <strong>100% zero teacher dependencies</strong> in a single forward pass:</p>
      <ul style="font-size: 14px; color: #b0aa9c; padding-left: 20px; line-height: 1.8;">
        <li><strong>High-Capacity Distilled Student (96.59M Params)</strong>: Fuses a full ConvNeXt-Base backbone (87.56M), 30-filter SRM high-pass spectral encoder (1.57M), Cross-Modal FPN (4.98M), 3-way classifier (920K), and a continuous 64x64 spatial heatmap decoder (1.55M). Runs in <strong>17.1 ms (FP16)</strong> and achieves 51.4% 3-way accuracy with superior real-photo specificity.</li>
        <li><strong>Ultra-Lightweight Student (4.67M Params)</strong>: MobileNet-V3 + SRM residual blocks designed for micro-devices and embedded systems (2.2 ms, 8.97 MB FP16).</li>
      </ul>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">DETERMINISTIC SPATIAL &amp; FREQUENCY PHYSICS ENGINES</h2>
      <ul style="font-size: 14px; color: #b0aa9c; padding-left: 20px; line-height: 1.8;">
        <li><strong>2D Radial FFT Power Decay Spectrum</strong>: Integrates 2D Fourier energy radially to assess high-frequency spectral falloff: $E(k) \propto k^{-\gamma}$. Synthetic images exhibit characteristic high-frequency slope deviations.</li>
        <li><strong>30-Filter SRM High-Pass Convolution</strong>: Computes directional second-order discrete derivatives ($R(x, y) = I(x, y) * K_{\text{srm}} - I(x, y)$) to expose camera Photo-Response Non-Uniformity (PRNU) versus synthetic upsampling patterns.</li>
        <li><strong>Laplacian Edge Variance</strong>: Measures local gradient discontinuities across suspected inpainting boundaries.</li>
      </ul>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">HARDWARE ACCELERATION &amp; QUANTIZATION</h2>
      <p style="font-size: 14px; color: #b0aa9c;">Serialized across <strong>FP32</strong> (full precision reference), <strong>FP16</strong> (Tensor Core GPU acceleration: 17.1 ms, 184 MB VRAM), and <strong>INT8</strong> (quantized edge execution: 7.5 ms, 92.5 MB footprint).</p>
    </div>
  `,

  dataset: `
    <div style="font-family: var(--system); color: var(--ivory); line-height: 1.75;">
      <h1 style="font-family: var(--condensed); font-size: 36px; color: var(--ivory); margin: 0 0 16px; letter-spacing: 1px;">DATASET GOVERNANCE &amp; OPEN REPOSITORIES</h1>
      <p style="font-size: 15px; color: #c5beaf; margin-bottom: 16px;">The model was trained across an audited, deduplicated corpus of <strong>over 103,000 forensic samples</strong> spanning diverse generators, camera sensors, and resolution scales. Below is the complete catalog of primary public benchmark datasets, research corpora, and external download links used in this project:</p>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 12px; letter-spacing: 0.5px;">PRIMARY DATASET CATALOG &amp; DOWNLOAD LINKS</h2>
      <div style="overflow-x: auto; margin-bottom: 28px;">
        <table style="width: 100%; border-collapse: collapse; font-size: 13px; text-align: left; background: rgba(0,0,0,0.3); border: 1px solid rgba(212, 175, 55, 0.2);">
          <thead>
            <tr style="background: rgba(212, 175, 55, 0.15); color: var(--brass-hi);">
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Dataset Name</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Primary Role</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Sample Count</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Resolution</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">External Link / Repository</th>
            </tr>
          </thead>
          <tbody>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">MS-COCO 2017</td>
              <td style="padding: 10px;">Authentic Real Photography Baseline</td>
              <td style="padding: 10px;">123,287 images</td>
              <td style="padding: 10px;">Variable (~640px)</td>
              <td style="padding: 10px;">
                <a href="https://cocodataset.org/#download" target="_blank" style="color: var(--brass-hi); text-decoration: underline; font-weight: 600;">cocodataset.org</a> | 
                <a href="https://huggingface.co/datasets/detection-datasets/coco" target="_blank" style="color: #9fe2bf; text-decoration: underline;">HuggingFace</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">OpenForensics (ICCV 2021)</td>
              <td style="padding: 10px;">Multi-Face Inpainting &amp; Localized Forgery</td>
              <td style="padding: 10px;">115,325 images</td>
              <td style="padding: 10px;">Multi-Scale</td>
              <td style="padding: 10px;">
                <a href="https://openforensics.github.io/" target="_blank" style="color: var(--brass-hi); text-decoration: underline; font-weight: 600;">openforensics.github.io</a> | 
                <a href="https://huggingface.co/datasets/OpenForensics/OpenForensics" target="_blank" style="color: #9fe2bf; text-decoration: underline;">HuggingFace</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">GenImage Benchmark (NeurIPS 2023)</td>
              <td style="padding: 10px;">Million-Scale Multi-Generator Corpus</td>
              <td style="padding: 10px;">1,331,167 images</td>
              <td style="padding: 10px;">512px &ndash; 1024px</td>
              <td style="padding: 10px;">
                <a href="https://github.com/GenImage-Dataset/GenImage" target="_blank" style="color: var(--brass-hi); text-decoration: underline; font-weight: 600;">GitHub GenImage</a> | 
                <a href="https://huggingface.co/datasets/GenImage" target="_blank" style="color: #9fe2bf; text-decoration: underline;">HuggingFace</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">WildFake Benchmark</td>
              <td style="padding: 10px;">Diffusion &amp; Autoregressive in-the-Wild</td>
              <td style="padding: 10px;">40,000+ images</td>
              <td style="padding: 10px;">512px &ndash; 1024px</td>
              <td style="padding: 10px;">
                <a href="https://github.com/li-ming-chen/WildFake" target="_blank" style="color: var(--brass-hi); text-decoration: underline; font-weight: 600;">GitHub WildFake</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">FFHQ (Flickr-Faces-HQ)</td>
              <td style="padding: 10px;">Studio Portrait Remediation Pool (Pore Realism)</td>
              <td style="padding: 10px;">70,000 images</td>
              <td style="padding: 10px;">1024 &times; 1024</td>
              <td style="padding: 10px;">
                <a href="https://github.com/NVlabs/ffhq-dataset" target="_blank" style="color: var(--brass-hi); text-decoration: underline; font-weight: 600;">NVlabs/ffhq-dataset</a> | 
                <a href="https://huggingface.co/datasets/Marqo/ffhq-1024" target="_blank" style="color: #9fe2bf; text-decoration: underline;">HuggingFace</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">DIV2K (Super-Resolution Dataset)</td>
              <td style="padding: 10px;">High-Resolution Natural Edge &amp; Texture Baseline</td>
              <td style="padding: 10px;">2,000 images</td>
              <td style="padding: 10px;">2K (2048 &times; 1080)</td>
              <td style="padding: 10px;">
                <a href="https://data.vision.ee.ethz.ch/cvl/DIV2K/" target="_blank" style="color: var(--brass-hi); text-decoration: underline; font-weight: 600;">ETHZ DIV2K Portal</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">AIDE Multi-View Frequency Corpus (CVPR 2024)</td>
              <td style="padding: 10px;">High-Pass Filter &amp; SRM Spectral Calibration</td>
              <td style="padding: 10px;">Universal Weights</td>
              <td style="padding: 10px;">Multi-Crop</td>
              <td style="padding: 10px;">
                <a href="https://github.com/aide-forensics/AIDE" target="_blank" style="color: var(--brass-hi); text-decoration: underline; font-weight: 600;">GitHub AIDE</a>
              </td>
            </tr>
            <tr>
              <td style="padding: 10px; font-weight: 600; color: #9fe2bf;">Project Manifests &amp; Training Splits</td>
              <td style="padding: 10px;">Governed Training &amp; Validation Splits</td>
              <td style="padding: 10px;">103,400+ entries</td>
              <td style="padding: 10px;">256px &ndash; 4096px</td>
              <td style="padding: 10px;">
                <a href="https://github.com/manansethia/ENTROPY-Track5-TikTokTechJam" target="_blank" style="color: #9fe2bf; text-decoration: underline; font-weight: 600;">ENTROPY GitHub Repo</a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 24px 0 10px;">GENERATOR FAMILIES COVERED (12+ AI FAMILIES)</h2>
      <ul style="font-size: 14px; color: #b0aa9c; padding-left: 20px; line-height: 1.8;">
        <li><strong>Diffusion Models</strong>: Stable Diffusion v1.4, v1.5, v2.1, SDXL, SD3, FLUX.1, Midjourney v4/v5/v6, DALL-E 2/3, Google Imagen, Adobe Firefly.</li>
        <li><strong>GAN &amp; Autoregressive Architectures</strong>: ProGAN, StyleGAN2, StyleGAN3, BigGAN, StarGAN, VQGAN.</li>
        <li><strong>Partial-AI Inpainting Datasets</strong>: Synthetic face inpainting, object removal, background generation, and Generative Fill with pixel-level ground truth masks.</li>
        <li><strong>Authentic Camera Archives</strong>: Uncompressed DSLR landscape collections, Nikon/Canon raw archives, mobile phone photo pools, and fine-art photography.</li>
      </ul>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">THE 4-TIER RESOLUTION STRATIFICATION (ANTI-SHORTCUT PROTOCOL)</h2>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 12px;">Generative detectors often learn spurious shortcuts (such as assuming high-resolution images are real and low-resolution images are fake). We enforced resolution-stratified training:</p>
      <ul style="font-size: 14px; color: #b0aa9c; padding-left: 20px; line-height: 1.8;">
        <li><strong>Low-Res (&lt;512px)</strong>: Social media thumbnails and compressed web imagery.</li>
        <li><strong>Mid-Res (512px &ndash; 1024px)</strong>: Standard generative diffusion outputs and camera photography.</li>
        <li><strong>High-Res (1024px &ndash; 2048px)</strong>: Commercial AI renders and DSLR camera outputs.</li>
        <li><strong>Ultra-High-Res (&gt;2048px)</strong>: 24MP&ndash;60MP authentic photographs paired with 4K synthetic renders.</li>
      </ul>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">THE STUDIO PORTRAIT REMEDIATION POOL</h2>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 12px;">To solve the critical problem where high-pass filters mistook authentic human skin pores for synthetic generator noise, we injected a curated studio portrait remediation pool (C1 Specialist) from FFHQ into the training pipeline, eliminating over 50% of real-photo false alarms.</p>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">STRICT BENCHMARK ISOLATION</h2>
      <p style="font-size: 14px; color: #b0aa9c;">All official challenge evaluation images (e.g. COCO val2017 and WildFake DALL-E Advanced) are strictly isolated using cryptographic SHA-256 exclusion. Zero benchmark images were used for training, distillation, or threshold tuning.</p>
    </div>
  `,

  lineage: `
    <div style="font-family: var(--system); color: var(--ivory); line-height: 1.75;">
      <h1 style="font-family: var(--condensed); font-size: 36px; color: var(--ivory); margin: 0 0 16px; letter-spacing: 1px;">MODEL HISTORY &amp; ENGINEERING EVOLUTION</h1>
      
      <div style="position: relative; padding-left: 24px; border-left: 2px solid rgba(212, 175, 55, 0.4); margin: 20px 0;">
        <div style="margin-bottom: 24px;">
          <strong style="color: var(--brass-hi); font-size: 16px;">V1: Dual-Stream Baseline (332M Params)</strong>
          <p style="font-size: 13px; color: #b0aa9c; margin: 4px 0 0;">Proved CLIP + ConvNeXt fusion concept. Failed under heavy JPEG compression (AUROC dropped from 0.94 to 0.71) due to rigid frequency weighting.</p>
        </div>

        <div style="margin-bottom: 24px;">
          <strong style="color: var(--brass-hi); font-size: 16px;">V2: AIDE Spectral Master (897.8M Params, ConvNeXt-XXL)</strong>
          <p style="font-size: 13px; color: #b0aa9c; margin: 4px 0 0;">Deep 30-filter SRM frequency analysis across 5D multi-crop tensors. Exceptional on pristine GANs, but generated false alarms on studio portraits due to sharp camera edge noise.</p>
        </div>

        <div style="margin-bottom: 24px;">
          <strong style="color: var(--brass-hi); font-size: 16px;">V3: Specialist System (C0&ndash;C7 + Learned Gating Router)</strong>
          <p style="font-size: 13px; color: #b0aa9c; margin: 4px 0 0;">Created 8 specialized models (C0 Generalist, C1 Portrait Remediation, C2 Multi-Frequency ViT, C4 ConvNeXt-Base, C5 divine2k, C6 EfficientNet, C7 ResNet50) coordinated by a 1.22K learned routing MLP.</p>
        </div>

        <div style="margin-bottom: 24px;">
          <strong style="color: var(--brass-hi); font-size: 16px;">V4: Partial-AI Prototype &amp; V4.3 Scale-Up Lessons</strong>
          <p style="font-size: 13px; color: #b0aa9c; margin: 4px 0 0;">V4.2 prototype proved multi-scale patch fusion (88.6% acc). Scaling to 49K samples in V4.3 exposed critical failure: severe class imbalance (7:1 real-to-partial) and &lt;5% edit area dilution collapsed partial AP to 18.7%.</p>
        </div>

        <div style="margin-bottom: 24px;">
          <strong style="color: var(--brass-hi); font-size: 16px;">V5: Cross-Attention Gated (CAG) Spatial Engine (31.1M Head)</strong>
          <p style="font-size: 13px; color: #b0aa9c; margin: 4px 0 0;">Introduced coordinate-aware cross-attention for pixel anomaly segmentation. Auditing revealed default ImageNet backbone weights, leading to the Master Fusion phase.</p>
        </div>

        <div style="margin-bottom: 24px;">
          <strong style="color: var(--brass-hi); font-size: 16px;">Master Unified Ensemble (1.82B Params, 11 Models)</strong>
          <p style="font-size: 13px; color: #b0aa9c; margin: 4px 0 0;">Compiled all 11 constituent teachers into a 3.47 GB sequential pipeline. High accuracy (56.8%) but heavy latency (1,252 ms) and excessive memory overhead.</p>
        </div>

        <div>
          <strong style="color: var(--brass-hi); font-size: 16px;">Final Standalone Distilled Student (96.59M Params) ⭐</strong>
          <p style="font-size: 13px; color: #b0aa9c; margin: 4px 0 0;">Distilled the knowledge of all 11 teachers into a single ConvNeXt-Base + SRM + FPN neural network. <strong>100% standalone</strong>, runs in <strong>17.1 ms (73x faster)</strong>, occupies 184 MB FP16 / 92 MB INT8, with superior real-photo specificity.</p>
        </div>
      </div>
    </div>
  `,

  releases: `
    <div style="font-family: var(--system); color: var(--ivory); line-height: 1.75;">
      <h1 style="font-family: var(--condensed); font-size: 36px; color: var(--ivory); margin: 0 0 16px; letter-spacing: 1px;">OFFICIAL MODEL RELEASES &amp; DOWNLOADS</h1>
      <p style="font-size: 15px; color: #c5beaf; margin-bottom: 16px;">All models are verified, tested, and cataloged. Click below to download weights directly for local execution:</p>

      <div style="overflow-x: auto; margin-bottom: 24px;">
        <table style="width: 100%; border-collapse: collapse; font-size: 13px; text-align: left; background: rgba(0,0,0,0.3); border: 1px solid rgba(212, 175, 55, 0.2);">
          <thead>
            <tr style="background: rgba(212, 175, 55, 0.15); color: var(--brass-hi);">
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Model Name</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Params</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Format</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Size</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">GPU Latency</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Direct Download</th>
            </tr>
          </thead>
          <tbody>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">HighCap Distilled (INT8) ⚡</td>
              <td style="padding: 10px;">96.59M</td>
              <td style="padding: 10px; color: var(--brass-hi);">INT8</td>
              <td style="padding: 10px;">92.5 MB</td>
              <td style="padding: 10px;">7.5 ms</td>
              <td style="padding: 10px;">
                <a href="https://github.com/manansethia/ENTROPY-Track5-TikTokTechJam/raw/main/checkpoints/distilled/highcap_distilled_forensic_model_int8.pt" target="_blank" style="display: inline-block; padding: 4px 10px; background: rgba(212, 175, 55, 0.2); border: 1px solid var(--brass-hi); border-radius: 3px; color: var(--brass-hi); text-decoration: none; font-size: 11px; font-weight: 600;">DOWNLOAD (.PT)</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">HighCap Distilled (FP16) ⭐</td>
              <td style="padding: 10px;">96.59M</td>
              <td style="padding: 10px; color: var(--brass-hi);">FP16</td>
              <td style="padding: 10px;">184.4 MB</td>
              <td style="padding: 10px;">17.1 ms</td>
              <td style="padding: 10px;">
                <a href="https://github.com/manansethia/ENTROPY-Track5-TikTokTechJam/releases" target="_blank" style="display: inline-block; padding: 4px 10px; background: rgba(212, 175, 55, 0.2); border: 1px solid var(--brass-hi); border-radius: 3px; color: var(--brass-hi); text-decoration: none; font-size: 11px; font-weight: 600;">DOWNLOAD (.PT)</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">HighCap Distilled (FP32)</td>
              <td style="padding: 10px;">96.59M</td>
              <td style="padding: 10px; color: var(--brass-hi);">FP32</td>
              <td style="padding: 10px;">368.6 MB</td>
              <td style="padding: 10px;">26.9 ms</td>
              <td style="padding: 10px;">
                <a href="https://github.com/manansethia/ENTROPY-Track5-TikTokTechJam/releases" target="_blank" style="display: inline-block; padding: 4px 10px; background: rgba(255, 255, 255, 0.1); border: 1px solid #888; border-radius: 3px; color: #ccc; text-decoration: none; font-size: 11px;">DOWNLOAD (.PT)</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">UltraLight Distilled (FP16)</td>
              <td style="padding: 10px;">4.67M</td>
              <td style="padding: 10px; color: var(--brass-hi);">FP16</td>
              <td style="padding: 10px;">8.97 MB</td>
              <td style="padding: 10px;">2.2 ms</td>
              <td style="padding: 10px;">
                <a href="https://github.com/manansethia/ENTROPY-Track5-TikTokTechJam/raw/main/checkpoints/distilled/master_distilled_forensic_model_fp16.pt" target="_blank" style="display: inline-block; padding: 4px 10px; background: rgba(212, 175, 55, 0.2); border: 1px solid var(--brass-hi); border-radius: 3px; color: var(--brass-hi); text-decoration: none; font-size: 11px; font-weight: 600;">DOWNLOAD (.PT)</a>
              </td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">UltraLight Distilled (INT8)</td>
              <td style="padding: 10px;">4.67M</td>
              <td style="padding: 10px; color: var(--brass-hi);">INT8</td>
              <td style="padding: 10px;">4.82 MB</td>
              <td style="padding: 10px;">1.8 ms</td>
              <td style="padding: 10px;">
                <a href="https://github.com/manansethia/ENTROPY-Track5-TikTokTechJam/raw/main/checkpoints/distilled/master_distilled_forensic_model_int8.pt" target="_blank" style="display: inline-block; padding: 4px 10px; background: rgba(212, 175, 55, 0.2); border: 1px solid var(--brass-hi); border-radius: 3px; color: var(--brass-hi); text-decoration: none; font-size: 11px; font-weight: 600;">DOWNLOAD (.PT)</a>
              </td>
            </tr>
            <tr>
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">Model C0 (Triple-Hybrid Champion)</td>
              <td style="padding: 10px;">735.0M</td>
              <td style="padding: 10px; color: var(--brass-hi);">FP32</td>
              <td style="padding: 10px;">1,470 MB</td>
              <td style="padding: 10px;">45.0 ms</td>
              <td style="padding: 10px;">
                <a href="https://github.com/manansethia/ENTROPY-Track5-TikTokTechJam/releases" target="_blank" style="display: inline-block; padding: 4px 10px; background: rgba(212, 175, 55, 0.2); border: 1px solid var(--brass-hi); border-radius: 3px; color: var(--brass-hi); text-decoration: none; font-size: 11px; font-weight: 600;">DOWNLOAD (.PT)</a>
              </td>
            </tr>
            <tr>
              <td style="padding: 10px; font-weight: 600; color: var(--ivory);">Master Unified Teacher Ensemble</td>
              <td style="padding: 10px;">1,818.5M</td>
              <td style="padding: 10px; color: var(--brass-hi);">FP16</td>
              <td style="padding: 10px;">3,470.2 MB</td>
              <td style="padding: 10px;">1,252.5 ms</td>
              <td style="padding: 10px;">
                <a href="https://github.com/manansethia/ENTROPY-Track5-TikTokTechJam/releases" target="_blank" style="display: inline-block; padding: 4px 10px; background: rgba(255, 255, 255, 0.1); border: 1px solid #888; border-radius: 3px; color: #ccc; text-decoration: none; font-size: 11px;">DOWNLOAD (.PT)</a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">HOW TO LOAD IN PYTHON (3 LINES)</h2>
      <pre style="background: rgba(0,0,0,0.5); padding: 14px; border: 1px solid rgba(212, 175, 55, 0.2); border-radius: 4px; font-family: var(--mono); font-size: 12px; color: var(--ivory); overflow-x: auto;">
import torch
from scripts.final.highcap_distilled_forensic_model import HighCapacityStudentForensicModel

model = HighCapacityStudentForensicModel().eval().cuda().half()
ckpt = torch.load("checkpoints/distilled/highcap_distilled_forensic_model_int8.pt")
model.load_state_dict(ckpt["model_state_dict"])
out = model(image_tensor_224) # Returns class_logits, probabilities, segmentation_heatmap</pre>
    </div>
  `,

  openforensics: `
    <div style="font-family: var(--system); color: var(--ivory); line-height: 1.75;">
      <h1 style="font-family: var(--condensed); font-size: 36px; color: var(--ivory); margin: 0 0 16px; letter-spacing: 1px;">OPEN FORENSICS &amp; REPRODUCIBILITY</h1>
      <p style="font-size: 15px; color: #c5beaf; margin-bottom: 16px;">We believe forensic AI systems must be fully transparent, verifiable, and reproducible. Black-box detectors that hide their architecture or weights cannot be trusted in high-stakes legal, journalistic, or intelligence settings.</p>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 24px 0 10px;">OPEN CLI INFERENCE</h2>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 12px;">Run local forensic analysis on any image using our open CLI:</p>
      <pre style="background: rgba(0,0,0,0.5); padding: 14px; border: 1px solid rgba(212, 175, 55, 0.2); border-radius: 4px; font-family: var(--mono); font-size: 12px; color: var(--ivory); overflow-x: auto;">
# Single Image Evaluation
python infer.py \
  --image test_inputs/sample.jpg \
  --checkpoint checkpoints/distilled/highcap_distilled_forensic_model_int8.pt \
  --device cuda

# Batch Directory Evaluation with Full Forensic Metadata
python predict.py \
  --input-dir ./test_images \
  --output predictions.json</pre>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">STANDARDIZED JSON FORENSIC SCHEMA</h2>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 12px;">All inference jobs emit machine-readable JSON forensic dossiers:</p>
      <pre style="background: rgba(0,0,0,0.5); padding: 14px; border: 1px solid rgba(212, 175, 55, 0.2); border-radius: 4px; font-family: var(--mono); font-size: 12px; color: var(--ivory); overflow-x: auto;">
[
  {
    "image_path": "test_images/sample1.jpg",
    "pred": 0.9142
  }
]</pre>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">GIT REPOSITORY &amp; MODEL WEIGHTS</h2>
      <p style="font-size: 14px; color: #b0aa9c;">Full project codebase, manifests, and documentation are hosted on GitHub: <a href="https://github.com/manansethia/ENTROPY-Track5-TikTokTechJam" target="_blank" style="color: var(--brass-hi); text-decoration: underline;">ENTROPY-Track5-TikTokTechJam</a>.</p>
    </div>
  `,

  wiki: `
    <div style="font-family: var(--system); color: var(--ivory); line-height: 1.75;">
      <h1 style="font-family: var(--condensed); font-size: 36px; color: var(--ivory); margin: 0 0 16px; letter-spacing: 1px;">FORENSIC COMPENDIUM &amp; MODEL WIKI</h1>
      <p style="font-size: 15px; color: #c5beaf; margin-bottom: 20px;">A comprehensive, deep-dive reference into the mechanics, dataset dynamics, specializations, physical blindspots, and mathematical foundations governing our forensic AI vision ecosystem.</p>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">1. SPECIALIST DOMAIN ANALYSIS: STRENGTHS &amp; WEAKNESSES</h2>
      <div style="overflow-x: auto; margin-bottom: 24px;">
        <table style="width: 100%; border-collapse: collapse; font-size: 13px; text-align: left; background: rgba(0,0,0,0.3); border: 1px solid rgba(212, 175, 55, 0.2);">
          <thead>
            <tr style="background: rgba(212, 175, 55, 0.15); color: var(--brass-hi);">
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Specialist</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Architecture</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Specialized Domain</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Why It Is Strong There</th>
              <th style="padding: 10px; border: 1px solid rgba(212, 175, 55, 0.2);">Known Vulnerability / Weakness</th>
            </tr>
          </thead>
          <tbody>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--brass-hi);">C0 (Champion Anchor)</td>
              <td style="padding: 10px;">CLIP ViT-L/14 + ConvNeXt</td>
              <td style="padding: 10px;">Generalist Full-AIGC</td>
              <td style="padding: 10px;">Combines macro-semantic realism with SRM wavelet residual features.</td>
              <td style="padding: 10px; color: #ff9999;">Misses localized inpainting covering &lt;5% of image canvas.</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--brass-hi);">C1 (Portrait Remediation)</td>
              <td style="padding: 10px;">ConvNeXt-Tiny + SRM Head</td>
              <td style="padding: 10px;">Human Faces &amp; Skin</td>
              <td style="padding: 10px;">Trained on studio lighting &amp; pores to suppress natural portrait false alarms.</td>
              <td style="padding: 10px; color: #ff9999;">Lower sensitivity on non-human textures (landscapes, text).</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--brass-hi);">C2 (SPAI Frequency ViT)</td>
              <td style="padding: 10px;">Multi-Frequency ViT</td>
              <td style="padding: 10px;">Wavelet &amp; DCT Artifacts</td>
              <td style="padding: 10px;">Detects subtle upsampling grid frequencies in uncompressed files.</td>
              <td style="padding: 10px; color: #ff9999;">Vulnerable to JPEG compression below Q60 which alters DCT grids.</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--brass-hi);">C3 (CommunityForensics ViT)</td>
              <td style="padding: 10px;">DINOv2 ViT-B/14</td>
              <td style="padding: 10px;">Dense Self-Supervised Features</td>
              <td style="padding: 10px;">Strong semantic segmentation of subtle unnatural textures.</td>
              <td style="padding: 10px; color: #ff9999;">High compute cost per patch; sensitive to heavy downscaling.</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--brass-hi);">C4 (ConvNeXt-Base)</td>
              <td style="padding: 10px;">ConvNeXt-Base (87.6M)</td>
              <td style="padding: 10px;">High-Resolution Renders</td>
              <td style="padding: 10px;">Trained on high-res crops (&gt;1024px); achieves 0.9767 individual AUROC.</td>
              <td style="padding: 10px; color: #ff9999;">Requires 384x384 input resolution, increasing compute overhead.</td>
            </tr>
            <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
              <td style="padding: 10px; font-weight: 600; color: var(--brass-hi);">V5-CAG (Spatial Head)</td>
              <td style="padding: 10px;">Cross-Attention Engine</td>
              <td style="padding: 10px;">Partial-AI Localization</td>
              <td style="padding: 10px;">Coordinate-guided cross-attention generates accurate pixel-level masks.</td>
              <td style="padding: 10px; color: #ff9999;">Used default ImageNet backbone weights in research prototype.</td>
            </tr>
            <tr>
              <td style="padding: 10px; font-weight: 600; color: #9fe2bf;">HighCap Distilled (96M) ⭐</td>
              <td style="padding: 10px;">ConvNeXt-Base + SRM + FPN</td>
              <td style="padding: 10px;">All-in-One Standalone</td>
              <td style="padding: 10px;">Distilled across all 11 teachers; 17.1 ms latency, 50% lower false positive rate.</td>
              <td style="padding: 10px; color: #9fe2bf;">None (Current recommended production model).</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">2. KNOWN FORENSIC BLINDSPOTS &amp; PHYSICAL FAILURE MODES</h2>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 12px;">Forensic models are physical measurement systems. Understanding their boundary conditions is essential:</p>
      
      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px;">
        <div style="background: rgba(255,255,255,0.03); border: 1px solid rgba(212,175,55,0.2); padding: 14px; border-radius: 4px;">
          <strong style="color: var(--brass-hi); font-size: 14px;">A. High-Resolution Scenic &amp; Landscape Captures</strong>
          <p style="font-size: 12px; color: #b0aa9c; margin: 6px 0 0;">Intricate natural patterns (pine needles, ocean spray, distant rock faces, mountain ridges) produce high spatial frequency variance that overlaps with generative diffusion noise. Models without multi-scale patch consensus can false-alarm on raw 4K/8K landscape captures.</p>
        </div>
        <div style="background: rgba(255,255,255,0.03); border: 1px solid rgba(212,175,55,0.2); padding: 14px; border-radius: 4px;">
          <strong style="color: var(--brass-hi); font-size: 14px;">B. Astrophotography &amp; Deep Sky Long-Exposures</strong>
          <p style="font-size: 12px; color: #b0aa9c; margin: 6px 0 0;">Astrophotography uses high sensor gain (ISO 6400&ndash;25600) and dark-frame subtraction, producing non-Gaussian Poisson shot noise and star point-spread functions (PSF) that confuse Fourier radial power decay curves.</p>
        </div>
        <div style="background: rgba(255,255,255,0.03); border: 1px solid rgba(212,175,55,0.2); padding: 14px; border-radius: 4px;">
          <strong style="color: var(--brass-hi); font-size: 14px;">C. UI Screenshots &amp; Digital Graphic Design</strong>
          <p style="font-size: 12px; color: #b0aa9c; margin: 6px 0 0;">Digital screenshots contain pure rasterized vector typography and rectangular solid-color regions with zero sensor Photo-Response Non-Uniformity (PRNU), causing edge-variance detectors to flag synthetic characteristics.</p>
        </div>
        <div style="background: rgba(255,255,255,0.03); border: 1px solid rgba(212,175,55,0.2); padding: 14px; border-radius: 4px;">
          <strong style="color: var(--brass-hi); font-size: 14px;">D. Subtle Non-Generative Photoshop Adjustments</strong>
          <p style="font-size: 12px; color: #b0aa9c; margin: 6px 0 0;">Lightroom Clarity sliders, Unsharp Mask, HDR tone-mapping, and selective color grading alter local gradient statistics. While non-generative, these adjustments modify the natural sensor noise floor and create physical boundary ambiguity.</p>
        </div>
      </div>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">3. MATHEMATICAL FORMULATIONS OF RESIDUAL FORENSICS</h2>
      <p style="font-size: 14px; color: #b0aa9c; margin-bottom: 12px;"><strong>Spatial Rich Model (SRM) High-Pass Filtering</strong>: A set of 30 specialized 5x5 convolution kernels that compute discrete directional derivatives:</p>
      <pre style="background: rgba(0,0,0,0.5); padding: 12px; border: 1px solid rgba(212, 175, 55, 0.2); font-family: var(--mono); font-size: 12px; color: var(--ivory);">R(x, y) = I(x, y) * K_srm - I(x, y)</pre>
      <p style="font-size: 14px; color: #b0aa9c; margin-top: 8px;">Suppressing low-frequency scene content reveals the sensor PRNU in camera images and generative upsampling lattices in synthetic images.</p>

      <p style="font-size: 14px; color: #b0aa9c; margin: 16px 0 8px;"><strong>2D Radial FFT Power Decay Spectrum</strong>: Measuring the radial energy profile of the Fourier magnitude:</p>
      <pre style="background: rgba(0,0,0,0.5); padding: 12px; border: 1px solid rgba(212, 175, 55, 0.2); font-family: var(--mono); font-size: 12px; color: var(--ivory);">E(k) = \int_{0}^{2\pi} |\mathcal{F}\{I\}(k \cos \theta, k \sin \theta)|^2 d\theta \propto k^{-\gamma}</pre>

      <h2 style="font-family: var(--condensed); font-size: 24px; color: var(--brass-hi); margin: 28px 0 10px;">4. SUMMARY: WHEN TO USE WHICH MODEL</h2>
      <ul style="font-size: 14px; color: #b0aa9c; padding-left: 20px; line-height: 1.8;">
        <li><strong>Web Application / Server Deployment</strong>: Use <strong>HighCap_96M_FP16</strong> (184 MB, 17.1 ms, standalone) or the live <strong>C0 Triple-Hybrid</strong> (735M).</li>
        <li><strong>Edge / Low-Memory Server</strong>: Use <strong>HighCap_96M_INT8</strong> (92.5 MB, 7.5 ms).</li>
        <li><strong>IoT / Mobile Client Device</strong>: Use <strong>UltraLight_4M_INT8</strong> (4.8 MB, 1.8 ms).</li>
        <li><strong>Forensic Research &amp; Benchmark Audit</strong>: Use <strong>MasterUnified_1.82B_FP16</strong> (11-teacher ensemble).</li>
      </ul>
    </div>
  `
};



// ============================================================================
// Initialization & Three.js 3D Workstation Scene Engine
// ============================================================================

let scene, camera, renderer;

document.addEventListener("DOMContentLoaded", () => {
  initThreeScene();
  initDragAndDrop();
  checkBackendHealth();
  renderEvidenceDeck();
});

function checkBackendHealth() {
  fetch(`${STATE.apiBaseUrl}/health`)
    .then(res => res.json())
    .then(data => {
      const badge = document.getElementById("backend-status-text");
      if (badge) {
        const isReady = data.status === "online" && (data.model === "ready" || data.model_loaded === true);
        badge.innerText = isReady
          ? "ANALYSIS ENGINE ONLINE"
          : "ANALYSIS ENGINE UNAVAILABLE";
      }
    })
    .catch(() => {
      const badge = document.getElementById("backend-status-text");
      if (badge) badge.innerText = "ANALYSIS ENGINE OFFLINE";
    });
}

function initThreeScene() {
  const canvas = document.getElementById("scene-canvas");
  if (!canvas || typeof THREE === "undefined") return;

  scene = new THREE.Scene();
  camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.1, 100);
  camera.position.set(0, 4.2, 7.5);
  camera.lookAt(0, 0, 0);

  renderer = new THREE.WebGLRenderer({ canvas, alpha: true, antialias: true });
  renderer.setSize(window.innerWidth, window.innerHeight);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));

  // Lights
  const ambientLight = new THREE.AmbientLight(0xfffaed, 1.2);
  scene.add(ambientLight);

  const dirLight = new THREE.DirectionalLight(0xffe8ba, 2.0);
  dirLight.position.set(5, 8, 4);
  scene.add(dirLight);

  const rimLight = new THREE.PointLight(0xb99855, 3.5, 12);
  rimLight.position.set(-4, 3, 2);
  scene.add(rimLight);

  // Load Poly Haven PBR Materials if available
  const texLoader = new THREE.TextureLoader();
  const feltTex = texLoader.load("/assets/materials/felt-color.jpg");
  const walnutTex = texLoader.load("/assets/materials/walnut-color.jpg");

  feltTex.wrapS = feltTex.wrapT = THREE.RepeatWrapping;
  feltTex.repeat.set(4, 3);
  walnutTex.wrapS = walnutTex.wrapT = THREE.RepeatWrapping;
  walnutTex.repeat.set(2, 2);

  // 3D Investigation Table Surface
  const tableGeo = new THREE.CylinderGeometry(5.8, 5.8, 0.4, 64);
  const tableMat = new THREE.MeshStandardMaterial({
    color: 0x123d2b,
    map: feltTex,
    roughness: 0.85,
    metalness: 0.05
  });
  const tableMesh = new THREE.Mesh(tableGeo, tableMat);
  tableMesh.position.set(0, -1.2, 0);
  tableMesh.rotation.x = 0.18;
  scene.add(tableMesh);

  // Walnut Bezel Ring
  const bezelGeo = new THREE.TorusGeometry(5.8, 0.28, 16, 64);
  const bezelMat = new THREE.MeshStandardMaterial({
    color: 0x2b160c,
    map: walnutTex,
    roughness: 0.4,
    metalness: 0.1
  });
  const bezelMesh = new THREE.Mesh(bezelGeo, bezelMat);
  bezelMesh.position.set(0, -1.18, 0);
  bezelMesh.rotation.x = Math.PI / 2 + 0.18;
  scene.add(bezelMesh);

  // Render the existing forensic table only; the roulette is intentionally
  // omitted so the header and hero remain visually clear.
  function animate() {
    requestAnimationFrame(animate);
    renderer.render(scene, camera);
  }
  animate();

  window.addEventListener("resize", () => {
    camera.aspect = window.innerWidth / window.innerHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(window.innerWidth, window.innerHeight);
  });
}

// ============================================================================
// File Staging & 3D Evidence Deck
// ============================================================================

function triggerFileInput() {
  const input = document.getElementById("file-input");
  if (input) input.click();
}

function initDragAndDrop() {
  const tray = document.getElementById("evidence-tray");
  if (!tray) return;

  ['dragenter', 'dragover'].forEach(name => {
    tray.addEventListener(name, (e) => {
      e.preventDefault();
      e.stopPropagation();
      tray.style.borderColor = "var(--brass-hi)";
    });
  });

  ['dragleave', 'drop'].forEach(name => {
    tray.addEventListener(name, (e) => {
      e.preventDefault();
      e.stopPropagation();
      tray.style.borderColor = "rgba(230, 238, 219, .28)";
    });
  });

  tray.addEventListener('drop', (e) => {
    const files = e.dataTransfer.files;
    if (files && files.length > 0) {
      stageUserFiles(Array.from(files));
    }
  });
}

function handleFilesSelected(event) {
  const files = Array.from(event.target.files);
  if (files.length > 0) {
    stageUserFiles(files);
  }
}

function stageUserFiles(files) {
  STATE.items = files.map((file, idx) => ({
    id: `AF-${Math.floor(1000 + Math.random() * 9000)}`,
    file: file,
    filename: file.name,
    title: file.name,
    url: URL.createObjectURL(file),
    dimensions: "",
    size: `${(file.size / 1024).toFixed(1)} KB`
  }));
  STATE.deckOffset = 0;
  STATE.stagedCardId = STATE.items[0]?.id || null;

  renderEvidenceDeck();
}

function compactFileName(filename, maxLength = 24) {
  if (!filename || filename.length <= maxLength) return filename || "UNTITLED IMAGE";
  const extensionIndex = filename.lastIndexOf(".");
  const extension = extensionIndex > 0 ? filename.slice(extensionIndex) : "";
  const stem = extension ? filename.slice(0, extensionIndex) : filename;
  const room = Math.max(6, maxLength - extension.length - 4);
  const head = Math.ceil(room * .58);
  const tail = Math.floor(room * .42);
  return `${stem.slice(0, head)}....${stem.slice(-tail)}${extension}`;
}

function loadDemoDeck() {
  STATE.items = [...DEMO_CASES];
  renderEvidenceDeck();
  showToast("Demo evidence deck loaded onto investigation table.");
}

function renderEvidenceDeck() {
  const deck = document.getElementById("evidence-deck");
  const headline = document.getElementById("tray-headline");
  const sessionCount = document.getElementById("session-count");
  const classifiedDecks = document.getElementById("classified-decks");
  const experience = document.getElementById("experience");

  if (classifiedDecks) classifiedDecks.style.display = "none";
  if (experience) experience.classList.remove("has-results");

  if (headline) headline.innerText = `${STATE.items.length} EXHIBITS STAGED`;
  if (sessionCount) sessionCount.innerText = `${STATE.items.length} ITEMS READY`;

  if (!deck) return;
  deck.innerHTML = "";

  // Keep a controlled, selectable window for larger batches. The full physical
  // stack is implied by depth while every visible card remains a usable target.
  const displayCount = Math.min(STATE.items.length, window.innerWidth <= 620 ? 4 : 5);
  const maxOffset = Math.max(0, STATE.items.length - displayCount);
  STATE.deckOffset = Math.min(STATE.deckOffset, maxOffset);
  const visibleItems = STATE.items.slice(STATE.deckOffset, STATE.deckOffset + displayCount);
  if (!visibleItems.some((item) => item.id === STATE.stagedCardId)) {
    STATE.stagedCardId = visibleItems[0]?.id || null;
  }

  for (let i = 0; i < displayCount; i++) {
    const item = visibleItems[i];
    const card = document.createElement("button");
    card.className = "evidence-card";
    card.dataset.id = item.id;
    card.setAttribute("aria-label", `Select exhibit ${item.id}: ${item.filename}`);
    card.setAttribute("aria-pressed", String(item.id === STATE.stagedCardId));
    if (item.id === STATE.stagedCardId) card.classList.add("is-selected");
    card.onclick = () => selectStagedCard(item.id);
    card.ondblclick = () => openInspection(item);

    // Preserve a compact physical deck; the classified piles use this same
    // dense stacking language after the deal.
    const x = (i * 3 - (displayCount - 1) * 1.5).toFixed(1);
    const y = (i * -2.5).toFixed(1);
    const z = (i * -3).toFixed(1);
    const r = (i * 1.1 - (displayCount - 1) * .55).toFixed(1);

    card.style.setProperty("--x", `${x}px`);
    card.style.setProperty("--y", `${y}px`);
    card.style.setProperty("--z", `${z}px`);
    card.style.setProperty("--r", `${r}deg`);
    card.style.zIndex = displayCount - i;

    const sealNum = (i + 1).toString().padStart(2, '0');

    card.innerHTML = `
      <div class="card-shell">
        <img class="card-photo" src="${item.url}" alt="${item.filename}">
        <div class="card-seal">${sealNum}</div>
        <div class="card-meta">
          <div>
            <strong>${item.id}</strong>
            <small title="${item.filename}">${compactFileName(item.filename).toUpperCase()}</small>
          </div>
          <span>${item.dimensions || '2048 × 2048'}</span>
        </div>
      </div>
    `;

    deck.appendChild(card);
  }

  deck.onwheel = (event) => {
    if (STATE.items.length <= displayCount) return;
    event.preventDefault();
    const nextOffset = Math.max(0, Math.min(maxOffset, STATE.deckOffset + (event.deltaY > 0 ? 1 : -1)));
    if (nextOffset !== STATE.deckOffset) {
      STATE.deckOffset = nextOffset;
      renderEvidenceDeck();
    }
  };

  deck.querySelectorAll(".evidence-card").forEach((card, hoveredIndex) => {
    card.addEventListener("pointerenter", () => {
      deck.querySelectorAll(".evidence-card").forEach((other, index) => {
        const direction = Math.sign(index - hoveredIndex);
        other.style.setProperty("--hover-shift", index === hoveredIndex ? "0px" : `${direction * Math.max(7, 22 - Math.abs(index - hoveredIndex) * 4)}px`);
      });
    });
    card.addEventListener("pointerleave", () => {
      deck.querySelectorAll(".evidence-card").forEach((other) => other.style.setProperty("--hover-shift", "0px"));
    });
  });
}

function selectStagedCard(id) {
  STATE.stagedCardId = id;
  document.querySelectorAll("#evidence-deck .evidence-card").forEach((card) => {
    const selected = card.dataset.id === id;
    card.classList.toggle("is-selected", selected);
    card.setAttribute("aria-pressed", String(selected));
  });
}

// ============================================================================
// Analysis Sequence: Laser Scan -> 3D Shuffle -> 3-Deck Deal
// ============================================================================

async function runAnalysis() {
  if (STATE.items.length === 0 || STATE.isAnalyzing) return;
  STATE.isAnalyzing = true;

  const analyzeBtn = document.getElementById("analyze-button");
  const tray = document.getElementById("evidence-tray");
  const statusWrap = document.getElementById("analysis-status");
  const timer = document.getElementById("status-timer");

  if (analyzeBtn) analyzeBtn.disabled = true;
  if (tray) tray.classList.add("is-scanning");
  if (statusWrap) statusWrap.style.display = "flex";

  const steps = [
    { id: "step-1", time: "0.08s", delay: 350 },
    { id: "step-2", time: "0.19s", delay: 400 },
    { id: "step-3", time: "0.34s", delay: 450 },
    { id: "step-4", time: "0.52s", delay: 550 },
    { id: "step-5", time: "0.68s", delay: 400 }
  ];

  for (let s of steps) {
    document.querySelectorAll(".analysis-status li").forEach(li => li.classList.remove("active"));
    const el = document.getElementById(s.id);
    if (el) {
      el.classList.add("active", "done");
    }
    if (timer) timer.innerText = s.time;
    await new Promise(r => setTimeout(r, s.delay));
  }

  // Demo cards stay explicitly labeled as demo content. Uploaded evidence always
  // requires the live model service; failed requests never receive invented scores.
  if (STATE.items[0] && STATE.items[0].verdict) {
    STATE.results = [...STATE.items];
  } else {
    try {
      const formData = new FormData();
      STATE.items.forEach(it => formData.append("files", it.file));
      formData.append("session_id", getAnalysisSessionId());
      const res = await fetch(`${STATE.apiBaseUrl}/analyze/batch`, { method: "POST", body: formData });
      if (!res.ok) {
        const error = await res.json().catch(() => ({}));
        throw new Error(error.detail || "Verified forensic analysis is unavailable.");
      }
      const data = await res.json();
      STATE.results = data.results.map((result, i) => toEvidenceCard(result, STATE.items[i]));
    } catch (e) {
      if (tray) tray.classList.remove("is-scanning");
      if (analyzeBtn) analyzeBtn.disabled = false;
      STATE.isAnalyzing = false;
      showToast(e.message || "Verified forensic analysis is unavailable.");
      return;
    }
  }

  // 3D Physical Card Shuffle Animation
  await executeCardShuffle();

  // 3-Deck Deal Animation
  await dealToThreePiles();

  if (tray) tray.classList.remove("is-scanning");
  if (analyzeBtn) analyzeBtn.disabled = false;
  STATE.isAnalyzing = false;
}

function toEvidenceCard(result, stagedItem) {
  const spatial = result.spatial_forensics || {};
  const metadata = result.metadata || {};
  const provenance = result.provenance || {};
  const fileInfo = result.file_info || {};
  const exposure = [metadata.exposure_time, metadata.aperture, metadata.iso ? `ISO ${metadata.iso}` : null]
    .filter(Boolean).join(" · ") || "NOT PRESENT";
  
  const rawProb = Number.isFinite(result.ai_probability)
    ? result.ai_probability
    : (Number.isFinite(result.probability_aigc)
      ? result.probability_aigc
      : (Number.isFinite(result.confidence) ? result.confidence : 0.5));

  return {
    ...result,
    id: stagedItem?.id || result.evidence_id,
    file: stagedItem?.file,
    url: stagedItem?.url,
    title: result.filename,
    dimensions: fileInfo.dimensions || stagedItem?.dimensions || "UNKNOWN",
    affected_area: result.affected_area_percentage ?? 0,
    probability_aigc: rawProb,
    ai_probability: rawProb,
    confidence: result.confidence ?? rawProb,
    verdict: result.verdict || "FULL_AIGC",
    verdict_badge: result.verdict_badge || (result.verdict === "REAL" ? "AUTHENTIC PHOTOGRAPH" : "SYNTHETIC IMAGE"),
    verdict_desc: result.verdict_description || result.verdict_desc || "Forensic evaluation completed.",
    sha256: fileInfo.sha256 || result.sha256,
    fft_high_freq: spatial.fft_high_frequency_ratio,
    srm_energy: spatial.srm_residual_energy,
    lap_var: spatial.laplacian_variance,
    inconsistency_status: spatial.inconsistency_status,
    spatial_forensics: spatial,
    camera: [metadata.camera_make, metadata.camera_model].filter(Boolean).join(" ") || "NOT PRESENT",
    lens: metadata.lens_model || "NOT PRESENT",
    exposure,
    c2pa: provenance.c2pa_status || "NOT DETECTED",
    provenance_headline: provenance.content_credentials_present ? "CONTENT CREDENTIALS PRESENT" : "NO VERIFIED C2PA MANIFEST",
    provenance_body: provenance.provenance_summary || "No verifiable provenance statement was found."
  };
}

async function executeCardShuffle() {
  const cards = Array.from(document.querySelectorAll("#evidence-deck .evidence-card"));
  if (cards.length === 0) return;

  cards.forEach((card) => card.classList.remove("is-selected"));
  if (!window.gsap) return;

  await new Promise((resolve) => {
    const timeline = window.gsap.timeline({ onComplete: resolve });
    // Lift, split, then interleave two physical sub-stacks before reforming.
    timeline.to(cards, { y: -28, duration: .22, ease: "power2.out" });
    cards.forEach((card, index) => {
      const side = index % 2 ? 1 : -1;
      timeline.to(card, {
        x: side * (86 + index * 7),
        y: -48 - (index % 3) * 13,
        rotation: side * (10 + index * 1.8),
        duration: .32,
        ease: "power3.out"
      }, .14 + index * .045);
    });
    cards.forEach((card, index) => {
      const side = index % 2 ? -1 : 1;
      timeline.to(card, {
        x: side * (26 + (index % 3) * 10),
        y: -13 - (index % 2) * 8,
        rotation: side * 3,
        duration: .25,
        ease: "power2.inOut"
      }, .50 + index * .05);
    });
    timeline.to(cards, { x: 0, y: 0, rotation: 0, duration: .32, ease: "power3.in", clearProps: "transform" }, "+=.03");
  });
}

async function dealToThreePiles() {
  const experience = document.getElementById("experience");
  const classifiedDecks = document.getElementById("classified-decks");
  if (experience) experience.classList.add("has-results");
  if (classifiedDecks) classifiedDecks.style.display = "block";

  STATE.piles = {
    REAL: STATE.results.filter(r => r.verdict === "REAL"),
    PARTIAL_AI: STATE.results.filter(r => r.verdict === "PARTIAL_AI"),
    FULL_AIGC: STATE.results.filter(r => r.verdict === "FULL_AIGC")
  };

  // Populate Counts
  const countReal = document.getElementById("count-real");
  const countPartial = document.getElementById("count-partial");
  const countFull = document.getElementById("count-full");

  if (countReal) countReal.innerText = STATE.piles.REAL.length;
  if (countPartial) countPartial.innerText = STATE.piles.PARTIAL_AI.length;
  if (countFull) countFull.innerText = STATE.piles.FULL_AIGC.length;

  const targets = {
    REAL: document.getElementById("cards-real"),
    PARTIAL_AI: document.getElementById("cards-partial"),
    FULL_AIGC: document.getElementById("cards-full")
  };
  const deck = document.getElementById("evidence-deck");
  const dealtCards = deck ? Array.from(deck.querySelectorAll(".evidence-card")) : [];
  const sourceRects = new Map(dealtCards.map((card) => [card, card.getBoundingClientRect()]));

  Object.values(targets).forEach((target) => { if (target) target.innerHTML = ""; });
  dealtCards.forEach((card) => {
    const item = STATE.results.find((result) => result.id === card.dataset.id);
    const target = targets[item?.verdict] || targets.FULL_AIGC;
    if (!target) return;
    const pileIndex = target.children.length;
    card.classList.remove("is-selected");
    card.classList.add("dealt-card");
    card.style.removeProperty("transform");
    card.style.setProperty("--x", `${(pileIndex - 1) * 13}px`);
    card.style.setProperty("--y", `${pileIndex * -7}px`);
    card.style.setProperty("--z", `${pileIndex * -8}px`);
    card.style.setProperty("--r", `${(pileIndex - 1) * 3.5}deg`);
    card.style.zIndex = String(20 + pileIndex);
    card.onclick = (event) => { event.stopPropagation(); openInspection(item); };
    card.ondblclick = null;
    target.appendChild(card);
  });

  const animations = dealtCards.map((card, index) => {
    const from = sourceRects.get(card);
    const to = card.getBoundingClientRect();
    if (!from || !to) return null;
    const x = from.left - to.left;
    const y = from.top - to.top;
    return card.animate([
      { transform: `translate(${x}px, ${y}px) rotate(${index % 2 ? 7 : -7}deg) scale(.95)`, opacity: .8 },
      { transform: `translate(${x * .45}px, ${y * .30 - 42}px) rotate(${index % 2 ? -3 : 3}deg) scale(1.04)`, offset: .56, opacity: 1 },
      { transform: "translate(0, 0) rotate(0deg) scale(1)" }
    ], { duration: 780, delay: index * 105, easing: "cubic-bezier(.2,.76,.17,1)" });
  }).filter(Boolean);
  await Promise.all(animations.map((animation) => animation.finished.catch(() => undefined)));

  // Smooth Scroll to Results
  classifiedDecks.scrollIntoView({ behavior: "smooth", block: "nearest" });
}

function populatePileCards(containerId, items) {
  const container = document.getElementById(containerId);
  if (!container) return;
  container.innerHTML = "";

  if (items.length === 0) {
    container.innerHTML = `<span style="font-family: var(--mono); font-size: 10px; color: #716d64; display: block; padding-top: 40px; text-align: center;">NO EXHIBITS</span>`;
    return;
  }

  const maxStack = Math.min(items.length, 5);
  for (let i = 0; i < maxStack; i++) {
    const item = items[i];
    const card = document.createElement("button");
    card.className = "evidence-card";
    card.onclick = (e) => {
      e.stopPropagation();
      openInspection(item);
    };

    const x = (i * 3 - (maxStack - 1) * 1.5).toFixed(1);
    const y = (i * -2.5).toFixed(1);
    const z = (i * -3).toFixed(1);
    const r = (i * 2 - (maxStack - 1) * 1).toFixed(1);

    card.style.setProperty("--x", `${x}px`);
    card.style.setProperty("--y", `${y}px`);
    card.style.setProperty("--z", `${z}px`);
    card.style.setProperty("--r", `${r}deg`);
    card.style.zIndex = maxStack - i;

    card.innerHTML = `
      <div class="card-shell">
        <img class="card-photo" src="${item.url}" alt="${item.filename}">
        <div class="card-seal">${(i + 1).toString().padStart(2, '0')}</div>
        <div class="card-meta">
          <div>
            <strong>${item.id}</strong>
            <small>${item.filename.toUpperCase()}</small>
          </div>
          <span>${item.dimensions || '2048 × 2048'}</span>
        </div>
      </div>
    `;

    container.appendChild(card);
  }
}

function openTopCard(type) {
  const items = STATE.piles[type];
  if (items && items.length > 0) {
    openInspection(items[0]);
  }
}

// ============================================================================
// High-Resolution Forensic Inspection Workbench Modal
// ============================================================================

function openInspection(item) {
  STATE.selectedCard = item;
  const modal = document.getElementById("inspection");
  if (!modal) return;
  modal.classList.add("open");

  // Populate Header
  const caseIdEl = document.getElementById("inspect-case-id");
  const filenameEl = document.getElementById("inspect-filename");
  if (caseIdEl) caseIdEl.innerText = item.id;
  if (filenameEl) filenameEl.innerText = item.filename;

  // Workbench Base Image
  const imgEl = document.getElementById("workbench-img");
  if (imgEl) imgEl.src = item.transformed_url || item.url;

  // Verdict Section
  const vTitle = document.getElementById("inspect-verdict");
  const vDesc = document.getElementById("inspect-desc");
  const vTier = document.getElementById("verdict-tier");
  const aiProb = document.getElementById("metric-ai-prob");
  const affected = document.getElementById("metric-affected");

  if (vTitle) vTitle.innerText = item.verdict_badge || item.verdict;
  if (vDesc) vDesc.innerText = item.verdict_desc || "Forensic evaluation completed.";
  if (vTier) vTier.innerText = item.confidence_tier || "HIGH CONFIDENCE";
  const pVal = Number.isFinite(item.probability_aigc) ? item.probability_aigc : (Number.isFinite(item.ai_probability) ? item.ai_probability : item.confidence);
  if (aiProb) aiProb.innerText = Number.isFinite(pVal) ? `${(pVal * 100).toFixed(1)}%` : "NOT AVAILABLE";
  if (affected) affected.innerText = item.affected_area > 0 ? `${item.affected_area}% (LOCAL)` : `0.0% (GLOBAL)`;

  // Spectral & Noise Signals (Stream C)
  const valFft = document.getElementById("val-fft");
  const barFft = document.getElementById("bar-fft");
  const valSrm = document.getElementById("val-srm");
  const barSrm = document.getElementById("bar-srm");
  const valLap = document.getElementById("val-lap");
  const barLap = document.getElementById("bar-lap");
  const valInconst = document.getElementById("val-inconst");

  if (valFft) valFft.innerText = item.fft_high_freq ?? "NOT AVAILABLE";
  if (barFft) barFft.style.setProperty("--value", `${Math.min(100, Math.max(0, Number(item.fft_high_freq || 0) * 400))}%`);
  if (valSrm) valSrm.innerText = item.srm_energy ?? "NOT AVAILABLE";
  if (barSrm) barSrm.style.setProperty("--value", `${Math.min(100, Math.max(0, Number(item.srm_energy || 0) * 12))}%`);
  if (valLap) valLap.innerText = item.lap_var ?? "NOT AVAILABLE";
  if (barLap) barLap.style.setProperty("--value", `${Math.min(100, Math.max(0, Number(item.lap_var || 0) / 8))}%`);
  if (valInconst) {
    valInconst.innerText = item.inconsistency_status || "NOT AVAILABLE";
    valInconst.style.color = item.inconsistency_status === "ANOMALY_DETECTED" ? "var(--amber)" : "var(--emerald)";
  }

  // Model Consensus Gate Weights
  const valClip = document.getElementById("val-clip");
  const barClip = document.getElementById("bar-clip");
  const valSiglip = document.getElementById("val-siglip");
  const barSiglip = document.getElementById("bar-siglip");
  const valSrmGate = document.getElementById("val-srm-gate");
  const barSrmGate = document.getElementById("bar-srm-gate");

  if (valClip) valClip.innerText = "NOT EXPOSED";
  if (barClip) barClip.style.setProperty("--value", "0%");
  if (valSiglip) valSiglip.innerText = "NOT EXPOSED";
  if (barSiglip) barSiglip.style.setProperty("--value", "0%");
  if (valSrmGate) valSrmGate.innerText = "NOT EXPOSED";
  if (barSrmGate) barSrmGate.style.setProperty("--value", "0%");

  // Hardware & EXIF
  const metaCam = document.getElementById("meta-camera");
  const metaLens = document.getElementById("meta-lens");
  const metaExp = document.getElementById("meta-exp");
  const metaDim = document.getElementById("meta-dim");
  const metaC2pa = document.getElementById("meta-c2pa");
  const metaSha = document.getElementById("meta-sha");

  if (metaCam) metaCam.innerText = item.camera || "NOT PRESENT (STRIPPED)";
  if (metaLens) metaLens.innerText = item.lens || "N/A";
  if (metaExp) metaExp.innerText = item.exposure || "N/A";
  if (metaDim) metaDim.innerText = item.dimensions || "2048 × 2048";
  if (metaC2pa) metaC2pa.innerText = item.c2pa || "NOT DETECTED";
  if (metaSha) metaSha.innerText = item.sha256 ? `${item.sha256.substring(0, 16)}...` : "NOT AVAILABLE";

  // Provenance Stamp Text
  const provHead = document.getElementById("prov-headline");
  const provBody = document.getElementById("prov-body");
  if (provHead) provHead.innerText = item.provenance_headline || "NO VERIFIED PROVENANCE";
  if (provBody) provBody.innerText = item.provenance_body || "No provenance statement was detected.";

  const heatmap = item.spatial_forensics?.artifacts?.heatmap_overlay_base64;
  const heatmapField = document.getElementById("workbench-heatmap");
  if (heatmapField) heatmapField.style.backgroundImage = heatmap ? `url("data:image/png;base64,${heatmap}")` : "none";

  // Set default view mode
  setWorkbenchMode("HEAT");
}

function cycleInspection(direction) {
  const ordered = STATE.results.length ? STATE.results : STATE.items;
  if (!STATE.selectedCard || ordered.length < 2) return;
  const index = ordered.findIndex(item => item.id === STATE.selectedCard.id);
  const next = ordered[(index + direction + ordered.length) % ordered.length];
  if (next) openInspection(next);
}

function closeInspection() {
  const modal = document.getElementById("inspection");
  if (modal) modal.classList.remove("open");
}

function buildInteractivePatchGrid(item) {
  const patchGrid = document.getElementById("workbench-patches");
  const readout = document.getElementById("workbench-readout");
  if (!patchGrid) return;
  patchGrid.innerHTML = "";

  for (let row = 0; row < 6; row++) {
    for (let col = 0; col < 8; col++) {
      const cell = document.createElement("div");
      cell.className = "patch-cell";
      
      const isTarget = false;

      cell.onmouseenter = () => {
        document.querySelectorAll(".patch-cell").forEach(c => c.classList.remove("active"));
        cell.classList.add("active");
        if (readout) {
          readout.classList.add("show");
          readout.innerHTML = `PATCH [${row}, ${col}]<br>LOCALIZED PATCH-LEVEL SCORES ARE NOT EXPOSED BY THIS MODEL.`;
        }
      };

      patchGrid.appendChild(cell);
    }
  }
}

function setWorkbenchMode(mode) {
  STATE.activeMode = mode;
  const workbench = document.getElementById("workbench");
  const overlayCanvas = document.getElementById("workbench-overlay");
  const opacityWrap = document.getElementById("opacity-wrap");
  const readout = document.getElementById("workbench-readout");

  document.querySelectorAll(".view-controls button").forEach(b => b.classList.remove("active"));
  const btn = document.getElementById(`mode-${mode.toLowerCase()}`);
  if (btn) btn.classList.add("active");

  if (!workbench) return;
  workbench.className = "image-workbench";
  if (overlayCanvas) {
    const ctx = overlayCanvas.getContext("2d");
    ctx.clearRect(0, 0, overlayCanvas.width, overlayCanvas.height);
  }
  if (opacityWrap) opacityWrap.style.display = "none";
  if (readout) readout.classList.remove("show");

  const card = STATE.selectedCard;

  if (mode === "ORIG") {
    // Clean original photo
  } else if (mode === "HEAT") {
    workbench.classList.add("show-heatmap");
    if (opacityWrap) opacityWrap.style.display = "flex";
  } else if (mode === "PATCH") {
    workbench.classList.add("show-patches");
  } else if (mode === "REGION") {
    showToast("Region bounds are not available from this inference model. Use the measured heatmap instead.");
  } else if (mode === "SRM") {
    renderCanvasSRM(card);
  } else if (mode === "FFT") {
    renderCanvasFFT(card);
  }
}

function adjustHeatOpacity(val) {
  const workbench = document.getElementById("workbench");
  const out = document.getElementById("opacity-out");
  if (workbench) workbench.style.setProperty("--heatmap-opacity", (val / 100).toString());
  if (out) out.innerText = `${val}%`;
}

async function applyPreviewTransform() {
  const card = STATE.selectedCard;
  if (!card?.file) {
    showToast("Transform previews are available for uploaded evidence, not the demo deck.");
    return;
  }
  const formData = new FormData();
  formData.append("file", card.file);
  formData.append("session_id", getAnalysisSessionId());
  formData.append("source_evidence_id", card.evidence_id || card.id);
  formData.append("jpeg_quality", document.getElementById("transform-quality")?.value || "85");
  formData.append("blur_radius", document.getElementById("transform-blur")?.value || "0");
  formData.append("crop_percent", document.getElementById("transform-crop")?.value || "100");
  try {
    const response = await fetch(`${STATE.apiBaseUrl}/v1/transform-preview`, { method: "POST", body: formData });
    const payload = await response.json();
    if (!response.ok) throw new Error(payload.detail || "Transformation preview failed.");
    const transformed = toEvidenceCard(payload.transformed_result, card);
    Object.assign(card, transformed, { transformed_url: payload.image_data_url, transform_job: payload.job });
    const image = document.getElementById("workbench-img");
    if (image) image.src = card.transformed_url;
    openInspection(card);
    const delta = payload.comparison?.probability_change;
    const comparison = delta == null ? "" : ` AI probability ${delta >= 0 ? "+" : ""}${(delta * 100).toFixed(1)} pts.`;
    showToast(`TRANSFORM ${payload.job.state.toUpperCase()}: ${payload.notice}${comparison}`);
  } catch (error) {
    showToast(error.message || "Transformation preview failed.");
  }
}

function renderCanvasSRM(card) {
  renderArtifactCanvas(card, "srm_residual_base64");
}

function renderCanvasFFT(card) {
  renderArtifactCanvas(card, "fft_spectrum_base64");
}

function renderArtifactCanvas(card, artifactName) {
  const canvas = document.getElementById("workbench-overlay");
  if (!canvas) return;
  canvas.width = 512;
  canvas.height = 512;
  const ctx = canvas.getContext("2d");
  const encoded = card.spatial_forensics?.artifacts?.[artifactName];
  if (!encoded) return;
  const image = new Image();
  image.onload = () => ctx.drawImage(image, 0, 0, canvas.width, canvas.height);
  image.src = `data:image/png;base64,${encoded}`;
}

function replayStage(stage) {
  STATE.activeReplayStage = stage;
  document.querySelectorAll(".replay button").forEach(b => b.classList.remove("active"));
  const btn = document.getElementById(`step-${stage}`);
  if (btn) btn.classList.add("active");

  const workbench = document.getElementById("workbench");
  if (stage === "ingest") {
    setWorkbenchMode("ORIG");
  } else if (stage === "global") {
    setWorkbenchMode("HEAT");
  } else if (stage === "local") {
    setWorkbenchMode("SRM");
  } else if (stage === "prov") {
    setWorkbenchMode("ORIG");
    if (workbench) workbench.classList.add("show-provenance");
  } else if (stage === "verdict") {
    setWorkbenchMode("HEAT");
  }
}

// ============================================================================
// Dossier Export Engine
// ============================================================================

function exportDossier(format) {
  const card = STATE.selectedCard || DEMO_CASES[0];
  if (!card) return;

  if (format === "JSON") {
    const reportData = {
      case_id: card.id,
      timestamp: new Date().toISOString(),
      image_filename: card.filename,
      dimensions: card.dimensions,
      sha256_checksum: card.sha256,
      assessment: {
        verdict: card.verdict,
        verdict_badge: card.verdict_badge,
        ai_probability: card.probability_aigc,
        affected_area_percentage: card.affected_area,
        confidence_tier: card.confidence_tier
      },
      model: {
        name: "Triple-Hybrid Champion",
        version: "v4.3-REM-A",
        parameters: "735M (735,038,561)",
        host: "Private inference service"
      },
      spatial_forensics: {
        fft_high_freq_ratio: card.fft_high_freq,
        srm_noise_energy: card.srm_energy,
        laplacian_variance: card.lap_var,
        inconsistency_status: card.inconsistency_status
      },
      consensus_gate_weights: {
        clip_vit_l14: card.gate_clip,
        siglip_so400m: card.gate_siglip,
        srm_wavelet_trunk: card.gate_srm
      },
      provenance: {
        c2pa_status: card.c2pa,
        headline: card.provenance_headline,
        summary: card.provenance_body
      },
      camera_exif: {
        camera_model: card.camera,
        lens_model: card.lens,
        exposure: card.exposure
      }
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Forensic_Dossier_${card.id}.json`;
    a.click();
    showToast(`Dossier ${card.id} exported to JSON.`);
  } else if (format === "PRINT") {
    window.print();
  }
}

// ============================================================================
// Documentation Modals & Navigation
// ============================================================================

function openDocModal(tab) {
  const modal = document.getElementById("doc-modal");
  const title = document.getElementById("doc-modal-title");
  const content = document.getElementById("doc-modal-content");

  const titleMap = {
    about: "WHY THIS MATTERS",
    technology: "TRIPLE-HYBRID ARCHITECTURE",
    dataset: "DATASET GOVERNANCE",
    lineage: "MODEL HISTORY & EVOLUTION",
    releases: "MODEL RELEASES & DOWNLOADS",
    openforensics: "OPEN FORENSICS & REPRODUCIBILITY",
    wiki: "FORENSIC COMPENDIUM & MODEL WIKI"
  };

  if (title) title.innerText = titleMap[tab] || "DOCUMENTATION";
  if (content) content.innerHTML = DOC_CONTENTS[tab] || `<p>Documentation ready.</p>`;
  if (modal) modal.classList.add("open");
}

function closeDocModal() {
  const modal = document.getElementById("doc-modal");
  if (modal) modal.classList.remove("open");
}

function showSection(name) {
  if (name === "analyze") {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }
}

function showToast(msg) {
  const toast = document.getElementById("toast");
  if (!toast) return;
  toast.innerText = msg;
  toast.classList.add("show");
  setTimeout(() => toast.classList.remove("show"), 3200);
}
