"""
Production Deployment Configuration for AIGC Robust Detector
AUTOGENERATED BY finalize_production_champion.py
"""

import os
from pathlib import Path
from pydantic import BaseModel, Field

DEFAULT_CHECKPOINT_PATH = Path("/home/manan/aigc_robust_detection/checkpoints/production/final_champion_frozen_model.pt")

class DeploymentConfig(BaseModel):
    # Model Identification & Governance Integrity
    model_name: str = "ScientificVisionDetector-ConfigA"
    champion_origin: str = "REM-A_Epoch3"
    checkpoint_path: str = str(DEFAULT_CHECKPOINT_PATH)
    expected_model_sha256: str = "91a6a3814c30f0b62f7b63e63fa81fe595c83b9edf91733ef9a8d3358e133438"
    parameter_hash: str = "813f243557810e64c85c8ad4519a3bc2e1b23d8545d1d493ff34fb5cff94e3ae"
    total_parameters: int = 735038561
    trainable_parameters: int = 32013809
    frozen_parameters: int = 703024752
    preprocessing_version: str = "dual_vit_224_standard"
    class_mapping: dict = {"0": "REAL", "1": "AIGC"}
    
    # Inference Defaults
    device: str = Field(default_factory=lambda: "cuda:0" if os.environ.get("CUDA_VISIBLE_DEVICES") != "" and os.path.exists("/dev/nvidia0") else "cpu")
    torch_dtype: str = "bfloat16"
    batch_size: int = 32
    max_image_dimension: int = 4096
    
    # Calibration & Operating Thresholds
    temperature_scaling: float = 1.523021
    threshold_standard: float = 0.500000
    threshold_low_fpr_10: float = 0.726040
    threshold_low_fpr_05: float = 0.931237
    threshold_low_fpr_01: float = 0.984399
    threshold_low_fpr_005: float = 0.990601
    threshold_low_fpr_001: float = 0.994351
    
    # Operating Points
    operating_thresholds: dict = {
    "FPR<=1.00%": {
        "target_fpr": 0.01,
        "achieved_fpr": 0.01,
        "empirical_tpr": 0.9924,
        "calibrated_threshold": 0.7260404825210571
    },
    "FPR<=0.50%": {
        "target_fpr": 0.005,
        "achieved_fpr": 0.0048,
        "empirical_tpr": 0.989,
        "calibrated_threshold": 0.9312365055084229
    },
    "FPR<=0.10%": {
        "target_fpr": 0.001,
        "achieved_fpr": 0.001,
        "empirical_tpr": 0.9782,
        "calibrated_threshold": 0.9843991994857788
    },
    "FPR<=0.05%": {
        "target_fpr": 0.0005,
        "achieved_fpr": 0.0004,
        "empirical_tpr": 0.9652,
        "calibrated_threshold": 0.9906008243560791
    },
    "FPR<=0.01%": {
        "target_fpr": 0.0001,
        "achieved_fpr": 0.0,
        "empirical_tpr": 0.925,
        "calibrated_threshold": 0.9943506717681885
    }
}
    
    # Normalization
    input_resolution: int = 224
    norm_mean: list = [0.48145466, 0.4578275, 0.40821073]
    norm_std: list = [0.26862954, 0.26130258, 0.27577711]

config = DeploymentConfig()
